#!/bin/bash

if [ ! -e ~/.taturepo ]; then
    cp /usr/share/doc/tatu-repo-devel/examples/taturepo.sample ~/.taturepo
fi

if [ ! -e ~/.pbuilderrc ]; then
    cp /usr/share/doc/tatu-repo-devel/examples/pbuilderrc ~/.pbuilderrc
fi

if [ ! -e ~/.devscripts ]; then
    cp /usr/share/doc/tatu-repo-devel/examples/devscripts ~/.devscripts
fi
